name = "mon-site"
account_id = "ed504140ebe99ca7d8ccffd88aa71f56"

main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"

build.command = "npm run build"

compatibility_date = "2021-11-12"
workers_dev = false
[[vars]]
VITE_SPOTIFY_CLIENT_ID = "e618a49ff9514890aea2d1414a44b334"
VITE_SPOTIFY_CLIENT_SECRET = "4728493812064edc93c7a7551c839285"
VITE_SPOTIFY_REFRESH_TOKEN = "AQCxLXdCoL3U6L7Q1v-KwbBwFkMOhrMaaQN_MPSNHUg_0MV25DNpls8kGH2yq1CKgQ0JzRWGSqWA2whOjZpoaK9xupXVlkg0Cd9ZiaoPDpooPgJksOglJDZG_Sk8-S_w5s0"
VITE_SPOTIFY_BASIC = "ZTYxOGE0OWZmOTUxNDg5MGFlYTJkMTQxNGE0NGIzMzQ6NDcyODQ5MzgxMjA2NGVkYzkzYzdhNzU1MWM4MzkyODU="